/* Marginalia — nabor citatov za "Misel dneva".
   Format vsake vrstice: "besedilo|avtor". Prazne vrstice ločujejo sklope. */
export const QUOTES = [
"Vem, da nič ne vem.|Sokrat",
"Nepregledano življenje ni vredno življenja.|Sokrat",
"Začetek je najpomembnejši del vsakega dela.|Platon",
"Vsak človek je toliko vreden, kolikor je vredno to, za kar si prizadeva.|Mark Avrelij",
"Sreča tvojega življenja je odvisna od kakovosti tvojih misli.|Mark Avrelij",
"Ne razpravljaj več o tem, kakšen naj bi bil dober človek. Bodi to.|Mark Avrelij",
"Zjutraj si reci: danes bom srečal vsiljivega, nehvaležnega, prevzetnega. Vse to jih doleti iz nevednosti o dobrem in zlem.|Mark Avrelij",
"Kar je ovira na poti, postane pot.|Mark Avrelij",
"Nismo vznemirjeni zaradi stvari, ampak zaradi mnenj o njih.|Epiktet",
"Nekatere stvari so v naši moči, druge ne.|Epiktet",
"Nihče ni svoboden, kdor ni gospodar samega sebe.|Epiktet",
"Ni pomembno, kaj se ti zgodi, ampak kako se na to odzoveš.|Epiktet",
"Ni malo časa, ki ga imamo, ampak veliko ga zapravimo.|Seneka",
"Vsak dan začni z mislijo, da si dolžan živeti dobro.|Seneka",
"Kdor je povsod, ni nikjer.|Seneka",
"Trpimo bolj v domišljiji kot v resnici.|Seneka",
"Dokler se učiš živeti, si se moraš učiti vse življenje.|Seneka",
"Nobenega vetra ni ugodnega tistemu, ki ne ve, kam pluje.|Seneka",
"Vse teče.|Heraklit",
"Nihče ne stopi dvakrat v isto reko.|Heraklit",
"Značaj je človekova usoda.|Heraklit",
"Smo to, kar vedno znova počnemo. Odličnost torej ni dejanje, ampak navada.|Aristotel",
"Znamenje izobraženega duha je, da lahko misel premisli, ne da bi jo sprejel.|Aristotel",
"Korenine izobrazbe so grenke, sadovi pa sladki.|Aristotel",
"Vsi ljudje po naravi hrepenijo po vedenju.|Aristotel",
"Prijatelj je ena duša v dveh telesih.|Aristotel",
"Pot tisočih milj se začne z enim korakom.|Lao Ce",
"Kdor pozna druge, je moder; kdor pozna sebe, je razsvetljen.|Lao Ce",
"Kdor je zadovoljen s tem, kar ima, je bogat.|Lao Ce",
"Narava se nikoli ne mudi, pa vendar je vse opravljeno.|Lao Ce",
"Ni pomembno, kako počasi greš, dokler se ne ustaviš.|Konfucij",
"Kdor se uči brez razmišljanja, je izgubljen; kdor razmišlja brez učenja, je v nevarnosti.|Konfucij",
"Rečeš mi in pozabim, pokažeš mi in si zapomnim, vključiš me in razumem.|Konfucij",
"Življenje je zares preprosto, a mi vztrajamo, da bi ga zapletli.|Konfucij",
"Kdor premakne goro, začne z odnašanjem majhnih kamnov.|Konfucij",
"Soba brez knjig je kot telo brez duše.|Ciceron",
"Če imaš vrt in knjižnico, imaš vse, kar potrebuješ.|Ciceron",
"Ne vedeti, kaj se je zgodilo pred tvojim rojstvom, pomeni ostati vedno otrok.|Ciceron",
"Nobena naloga ni tako težka, kot je videti, če jo razdeliš na majhne dele.|Ciceron",
"Kapljica izdolbe kamen, ne s silo, ampak z vztrajnostjo.|Ovid",
"Zaupaj tistemu, ki je izkusil.|Vergil",
"Vsakemu je usoda dala svoj dan.|Vergil",
"Zgrabi dan, čim manj zaupaj jutrišnjemu.|Horacij",
"Kdor je začel, je opravil polovico. Upaj si biti moder.|Horacij",
"Zdravega duha v zdravem telesu.|Juvenal",
"Človek sem, nič človeškega mi ni tuje.|Terencij",
"Med velikimi in majhnimi dušami je razlika v tem, kar imajo za nemogoče.|Plutarh",
"Duh ni posoda, ki jo je treba napolniti, ampak drva, ki jih je treba prižgati.|Plutarh",
"Prišel sem, videl sem, zmagal sem.|Julij Cezar",
"Ljudje verjamejo predvsem tisto, kar si želijo.|Julij Cezar",

"Berem, da bi vedel, da nisem sam.|William Shakespeare",
"Nič ni ne dobro ne slabo, mišljenje to naredi.|William Shakespeare",
"Vemo, kaj smo, ne pa, kaj lahko postanemo.|William Shakespeare",
"Bodi zvest sebi.|William Shakespeare",
"Prihodnost je tam, kjer bomo preživeli preostanek življenja.|William Shakespeare",
"Beseda brez misli nikoli ne gre v nebo.|William Shakespeare",
"Kdor uči, se sam uči dvakrat.|Michel de Montaigne",
"Življenje samo ni ne dobro ne zlo; je prostor za dobro in zlo.|Michel de Montaigne",
"Najveličastnejša stvar na svetu je znati pripadati sebi.|Michel de Montaigne",
"Kdor se boji trpljenja, že trpi zaradi tega, česar se boji.|Michel de Montaigne",
"Mislim, torej sem.|René Descartes",
"Branje dobrih knjig je pogovor z najboljšimi ljudmi preteklih stoletij.|René Descartes",
"Srce ima svoje razloge, ki jih razum ne pozna.|Blaise Pascal",
"To pismo sem napisal daljše, ker nisem imel časa napisati krajšega.|Blaise Pascal",
"Vsa človeška nesreča izvira iz nezmožnosti, da bi človek mirno sedel v sobi.|Blaise Pascal",
"Presojaj človeka bolj po njegovih vprašanjih kot po odgovorih.|Voltaire",
"Odlično je sovražnik dobrega.|Voltaire",
"Zdravnikova naloga je zabavati bolnika, medtem ko narava zdravi bolezen.|Voltaire",
"Človek se rodi svoboden, povsod pa je v verigah.|Jean-Jacques Rousseau",
"Potrpljenje je grenko, a njegov sad je sladek.|Jean-Jacques Rousseau",
"Imej pogum uporabiti svoj razum.|Immanuel Kant",
"Znanost je urejeno znanje, modrost je urejeno življenje.|Immanuel Kant",
"Iz krivega lesa človeštva ni mogoče stesati nič povsem ravnega.|Immanuel Kant",
"Karkoli lahko storiš ali sanjaš, da lahko storiš, začni. Drznost ima v sebi genij, moč in čarovnijo.|Johann Wolfgang von Goethe",
"Ravnaj s človekom, kakršen bi lahko bil, in postal bo, kar bi lahko bil.|Johann Wolfgang von Goethe",
"Nič ni bolj strašnega kot dejavna nevednost.|Johann Wolfgang von Goethe",
"Zadostuje ne vedeti, moramo uporabiti; hoteti ne zadostuje, moramo storiti.|Johann Wolfgang von Goethe",
"Kdor ne pozna tujih jezikov, ne ve ničesar o svojem.|Johann Wolfgang von Goethe",
"Vsak dan bi moral človek slišati košček glasbe, prebrati dobro pesem in videti lepo sliko.|Johann Wolfgang von Goethe",
"Kdor hoče doseči nemogoče, mora poskusiti absurdno.|Miguel de Cervantes",
"Kdor bere veliko in hodi veliko, vidi veliko in ve veliko.|Miguel de Cervantes",
"Pripravi se na najhujše in upaj na najboljše.|Miguel de Cervantes",

"Naredi, kar zmoreš, s tem, kar imaš, tam, kjer si.|Theodore Roosevelt",
"Verjemi, da zmoreš, in si na pol poti.|Theodore Roosevelt",
"Primerjava je tat veselja.|Theodore Roosevelt",
"Zaupaj vase. Veš več, kot misliš, da veš.|Ralph Waldo Emerson",
"Kar leži za nami in kar leži pred nami, je malenkost v primerjavi s tem, kar leži v nas.|Ralph Waldo Emerson",
"Ne hodi tja, kamor pelje pot. Pojdi raje tja, kjer poti ni, in pusti sled.|Ralph Waldo Emerson",
"Vsak človek, ki ga srečam, mi je v nečem nadrejen; v tem se od njega učim.|Ralph Waldo Emerson",
"Navdušenje je mati vsakega napredka. Brez njega ni bilo nikoli doseženo nič velikega.|Ralph Waldo Emerson",
"Naredi stvar in imel boš moč.|Ralph Waldo Emerson",
"Pojdi samozavestno v smeri svojih sanj. Živi življenje, ki si ga zamislil.|Henry David Thoreau",
"Nezadostno ni, da si zaposlen; tudi mravlje so. Vprašanje je, s čim si zaposlen.|Henry David Thoreau",
"Bogastvo človeka se meri s številom stvari, ki jih zmore pustiti pri miru.|Henry David Thoreau",
"Zgradil sem gradove v zraku. Zdaj pod njih postavi temelje.|Henry David Thoreau",
"Vsaka knjiga je čarovnija, ki premaguje čas.|Carl Sagan",
"Nič na svetu ne more nadomestiti vztrajnosti.|Calvin Coolidge",
"Najboljši način napovedati prihodnost je, da jo ustvariš.|Abraham Lincoln",
"Skoraj vsak človek prenese nesrečo. Če hočeš preizkusiti njegov značaj, mu daj moč.|Abraham Lincoln",
"Rajši molčim in veljam za bedaka, kot da spregovorim in vsak dvom odpravim.|Abraham Lincoln",
"Če bi imel šest ur, da posekam drevo, bi prve štiri porabil za brušenje sekire.|Abraham Lincoln",
"Kdor bere, živi tisoč življenj; kdor ne, živi eno samo.|George R. R. Martin",
"Vsaka omejitev, ki jo priznamo, je zid, ki smo ga sami postavili.|Frederick Douglass",
"Lažje je zgraditi močne otroke kot popravljati zlomljene odrasle.|Frederick Douglass",
"Brez boja ni napredka.|Frederick Douglass",
"Ko preberem dobro knjigo, si želim, da bi življenje trajalo tri tisoč let.|Ralph Waldo Emerson",

"Klasika je knjiga, ki nikoli ni dokončala tega, kar ima povedati.|Italo Calvino",
"Človek, ki ne bere, nima nobene prednosti pred tistim, ki ne zna brati.|Mark Twain",
"Skrb je plačevanje dolga, ki ga morda nikoli ne boš imel.|Mark Twain",
"Dobrota je jezik, ki ga gluhi slišijo in slepi vidijo.|Mark Twain",
"Čez dvajset let te bodo bolj razočarale stvari, ki jih nisi storil, kot tiste, ki si jih.|Mark Twain",
"Skrivnost napredovanja je začeti.|Mark Twain",
"Vedno delaj prav. To bo nekatere razveselilo, ostale pa presenetilo.|Mark Twain",
"Bodi to, kar si, in povej, kar čutiš, kajti tisti, ki jim je mar, ne štejejo, in tisti, ki štejejo, jim ni mar.|Bernard M. Baruch",
"Bodi to, kar si. Vse ostalo je že zasedeno.|Oscar Wilde",
"Vsi smo v blatu, a nekateri gledajo v zvezde.|Oscar Wilde",
"Izkušnja je ime, ki ga dajemo svojim napakam.|Oscar Wilde",
"Če hočeš ljudem povedati resnico, jih nasmej, sicer te bodo ubili.|Oscar Wilde",
"Ljubezen do sebe je začetek vseživljenjske romance.|Oscar Wilde",
"Živeti je najredkejša stvar na svetu. Večina ljudi obstaja, to je vse.|Oscar Wilde",
"Vsak od nas ima svojo pot, po kateri mora hoditi sam.|Lev Tolstoj",
"Vsi razmišljajo o tem, kako spremeniti svet, nihče pa o tem, kako spremeniti sebe.|Lev Tolstoj",
"Najmočnejša bojevnika sta potrpljenje in čas.|Lev Tolstoj",
"Če hočeš biti srečen, bodi.|Lev Tolstoj",
"Prava življenjska naloga ni v tem, da hodiš pred drugimi, ampak da hodiš pred svojim včerajšnjim jazom.|Lev Tolstoj",
"Lepota bo rešila svet.|Fjodor Dostojevski",
"Skrivnost človekovega obstoja ni le v tem, da ostane živ, ampak da najde, za kaj živeti.|Fjodor Dostojevski",
"Nič ni lažje kot obsojati zlobneža; nič težjega kot ga razumeti.|Fjodor Dostojevski",
"Ljubi življenje bolj kot smisel življenja.|Fjodor Dostojevski",
"Ne opisuj mi, da je luna posijala; pokaži mi lesk svetlobe na razbitem steklu.|Anton Čehov",
"Znanje nima vrednosti, dokler ga ne uporabiš v praksi.|Anton Čehov",
"Človek je to, v kar verjame.|Anton Čehov",
"Kdor hoče videti mavrico, mora prenesti dež.|Anton Čehov",
"Kdor ima zakaj živeti, prenese skoraj vsak kako.|Friedrich Nietzsche",
"Kar nas ne ubije, nas okrepi.|Friedrich Nietzsche",
"Nihče ne more zate zgraditi mostu, po katerem moraš prečkati reko življenja.|Friedrich Nietzsche",
"Vedno je nekaj norosti v ljubezni. A vedno je tudi nekaj razuma v norosti.|Friedrich Nietzsche",
"Kdor se bori s pošastmi, naj pazi, da sam ne postane pošast.|Friedrich Nietzsche",
"Naloga ni videti, česar še nihče ni videl, ampak misliti, česar še nihče ni mislil o tem, kar vsi vidijo.|Arthur Schopenhauer",
"Zdravje ni vse, a brez zdravja je vse nič.|Arthur Schopenhauer",
"Vsakdo ima meje svojega vidnega polja za meje sveta.|Arthur Schopenhauer",
"Življenje se lahko razume le nazaj, živeti pa ga je treba naprej.|Søren Kierkegaard",
"Tvegati pomeni za trenutek izgubiti tla pod nogami. Ne tvegati pomeni izgubiti sebe.|Søren Kierkegaard",
"Ne obupaj nad tem, da si ne moreš zapomniti vsega, kar bereš.|Samuel Johnson",
"Kar se pridobi brez truda, se ceni brez veselja.|Samuel Johnson",
"Velika dela ne opravi moč, ampak vztrajnost.|Samuel Johnson",

"Ni sreče v posedovanju ali prejemanju, ampak samo v dajanju.|Henry Drummond",
"Ne štej dni, naredi, da dnevi štejejo.|Muhammad Ali",
"Vsak otrok je umetnik. Težava je, kako ostati umetnik, ko odrasteš.|Pablo Picasso",
"Navdih obstaja, a te mora najti pri delu.|Pablo Picasso",
"Dejanje je temeljni ključ vsakega uspeha.|Pablo Picasso",
"Ne skrbi za svoje težave z matematiko. Zagotavljam ti, da so moje še večje.|Albert Einstein",
"Domišljija je pomembnejša od znanja.|Albert Einstein",
"Če ne znaš razložiti preprosto, nisi dovolj dobro razumel.|Albert Einstein",
"Vsakdo je genij. A če boš ribo sodil po tem, kako pleza na drevo, bo vse življenje mislila, da je nesposobna.|Albert Einstein",
"V življenju se ni treba ničesar bati, treba je le razumeti.|Marie Curie",
"Nič v življenju se ni bati, le razumeti je treba. Zdaj je čas, da razumemo več, da bi se manj bali.|Marie Curie",
"Bodi manj radoveden do ljudi in bolj radoveden do idej.|Marie Curie",
"Kdor bere, ta potuje, ne da bi se premaknil.|Marcel Proust",
"Pravo odkritje ni v iskanju novih pokrajin, ampak v gledanju z novimi očmi.|Marcel Proust",
"Naj bomo hvaležni ljudem, ki nas osrečujejo; so čudoviti vrtnarji, ki dajo, da naše duše zacvetijo.|Marcel Proust",
"Bodi potrpežljiv do vsega, kar je v tvojem srcu nerešeno. Poskusi ljubiti sama vprašanja.|Rainer Maria Rilke",
"Edino potovanje je tisto navznoter.|Rainer Maria Rilke",
"Morda so vsi zmaji našega življenja princese, ki čakajo, da nas vidijo lepe in pogumne.|Rainer Maria Rilke",
"Knjiga mora biti sekira za zamrznjeno morje v nas.|Franz Kafka",
"Vsakdo, ki ohrani sposobnost videti lepoto, se nikoli ne postara.|Franz Kafka",
"Za branje potrebuješ tri stvari: knjigo, mir in nekoga, s komer boš o njej govoril.|Virginia Woolf",
"Knjige so zrcala; v njih vidiš le tisto, kar že nosiš v sebi.|Virginia Woolf",
"Nobene sreče ni večje od tega, da lahko sam odločaš, kako preživiš svoj dan.|Virginia Woolf",
"Kdor ni dobro jedel, ne more dobro misliti, dobro ljubiti in dobro spati.|Virginia Woolf",
"Svet se lomi na vseh nas, potem pa smo mnogi močni prav na zlomljenih mestih.|Ernest Hemingway",
"Ni nič plemenitega v tem, da si boljši od drugega. Prava plemenitost je biti boljši od svojega prejšnjega jaza.|Ernest Hemingway",
"Vsak človek ima svojo vrednost prav v tem, kar ga dela drugačnega.|André Gide",
"Ne moreš odkriti novih oceanov, dokler nimaš poguma izgubiti obalo izpred oči.|André Gide",
"Vse, kar potrebujem, je knjiga in kotiček, kjer me nihče ne moti.|Jane Austen",
"Ni večjega užitka kot branje.|Jane Austen",
"Nihče ni tako moder, da bi vedel vse.|Charles Dickens",
"Ni odveč nič, kar naredimo za drugega.|Charles Dickens",
"Vzemi si čas za vse, kar je vredno; hitrost je le videz napredka.|Charles Dickens",
"Kdor gleda navzven, sanja; kdor gleda navznoter, se prebudi.|Carl Gustav Jung",
"Nisem to, kar se mi je zgodilo. Sem to, kar izberem, da bom postal.|Carl Gustav Jung",
"Vse, kar nas moti pri drugih, nas lahko pripelje do razumevanja sebe.|Carl Gustav Jung",
"Bistvo je očem nevidno.|Antoine de Saint-Exupéry",
"Če hočeš zgraditi ladjo, ne zbiraj ljudi, da bi sekali les, ampak jih nauči hrepeneti po neskončnem morju.|Antoine de Saint-Exupéry",
"Cilj brez načrta je samo želja.|Antoine de Saint-Exupéry",
"Popolnost ni dosežena takrat, ko ni več česa dodati, ampak ko ni več česa odvzeti.|Antoine de Saint-Exupéry",

"Ne prosi za lažje življenje, prosi za več moči.|Bruce Lee",
"Znanje ni dovolj, uporabiti ga moramo. Volja ni dovolj, delati moramo.|Bruce Lee",
"Izobrazba ni priprava na življenje; izobrazba je življenje samo.|John Dewey",
"Izobrazba je najmočnejše orožje, s katerim lahko spremeniš svet.|Nelson Mandela",
"Zdi se vedno nemogoče, dokler ni storjeno.|Nelson Mandela",
"Bodi sprememba, ki jo želiš videti v svetu.|Mahatma Gandhi",
"Živi, kot da boš umrl jutri. Uči se, kot da boš živel večno.|Mahatma Gandhi",
"Sila ne izvira iz telesne zmožnosti, ampak iz neomajne volje.|Mahatma Gandhi",
"Nihče te ne more prizadeti brez tvojega privoljenja.|Eleanor Roosevelt",
"Prihodnost pripada tistim, ki verjamejo v lepoto svojih sanj.|Eleanor Roosevelt",
"Vsak dan naredi eno stvar, ki te je strah.|Eleanor Roosevelt",
"Veliki umi razpravljajo o idejah, povprečni o dogodkih, majhni o ljudeh.|Eleanor Roosevelt",
"Uspeh ni dokončen, neuspeh ni usoden; šteje pogum za nadaljevanje.|Winston Churchill",
"Optimist vidi priložnost v vsaki težavi.|Winston Churchill",
"Nikoli ne zapravi dobre krize.|Winston Churchill",
"Kdor ne bere, nima nobene prednosti pred tistim, ki ne zna brati.|Konfucij",
"Ni vsak dan dober, a v vsakem dnevu je nekaj dobrega.|Alice Morse Earle",
"Včeraj je zgodovina, jutri skrivnost, danes je darilo.|Alice Morse Earle",

"Le kdor se ne boji zablod, najde novo pot.|Ivan Cankar",
"Domovina je ena, nam vsem dodeljena.|Ivan Cankar",
"Beseda je bila dana človeku, da bi z njo povedal resnico.|Ivan Cankar",
"Kdor ljubi svoj narod, ga ne slavi, ampak mu služi.|Ivan Cankar",
"Manj slovenskih besed, več slovenskih dejanj.|Ivan Cankar",
"Ne stoj, kjer si; pojdi naprej, tudi če je pot temna.|Ivan Cankar",
"Žive naj vsi narodi, ki hrepene dočakat dan, da koder sonce hodi, prepir iz sveta bo pregnan.|France Prešeren",
"Kar je bilo, ne pride več nazaj.|France Prešeren",
"Le čevlje sodi naj Kopitar.|France Prešeren",
"Vse je zaman, kar človek stori brez ljubezni.|Josip Jurčič",
"Kdor hoče drugim svetiti, mora sam goreti.|Simon Gregorčič",
"Le vkup, le vkup, uboga gmajna.|Anton Aškerc",
"Kdor ne spoštuje svojega jezika, ne spoštuje samega sebe.|Primož Trubar",
"Stati inu obstati.|Primož Trubar",
"Berite, berite, ta bukve so vaše.|Primož Trubar",
"Ljubezen do domovine se pokaže v delu, ne v besedah.|Janez Trdina",
"Naj bo delo tvoja molitev.|Fran Levstik",
"Kdor išče lepoto, jo bo našel povsod.|Janez Mencinger",
"Vsak človek nosi v sebi svoj svet.|Zofka Kveder",
"Kdor se ne uči, ta zaostaja.|Fran Erjavec",

"Sreča je, kadar to, kar misliš, kar rečeš in kar storiš, sovpada.|Mahatma Gandhi",
"Modrost se začne v čudenju.|Sokrat",
"Skrivnost spremembe je, da vso energijo osredotočiš na gradnjo novega, ne na boj s starim.|Sokrat",
"Ne moreš poučiti človeka ničesar; lahko mu le pomagaš, da to odkrije v sebi.|Galileo Galilei",
"In vendar se vrti.|Galileo Galilei",
"Če sem videl dlje, je to zato, ker sem stal na ramenih velikanov.|Isaac Newton",
"Kar vemo, je kapljica; česar ne vemo, je ocean.|Isaac Newton",
"Sreča daje prednost pripravljenemu duhu.|Louis Pasteur",
"Ni preživela najmočnejša vrsta, ampak tista, ki se je najbolje prilagajala spremembam.|Charles Darwin",
"Nevednost pogosteje rodi samozavest kot znanje.|Charles Darwin",
"Enostavnost je najvišja stopnja dovršenosti.|Leonardo da Vinci",
"Učenje nikoli ne izčrpa duha.|Leonardo da Vinci",
"Že dolgo sem opazil, da ljudje, ki nekaj dosežejo, redko sedijo in čakajo, da se jim zgodi.|Leonardo da Vinci",
"Ovira ne more upogniti moje volje. Kdor je trdno odločen, ne omahne.|Leonardo da Vinci",
"Kdor ima veliko potrpljenja, lahko doseže karkoli.|Benjamin Franklin",
"Povej mi in pozabim, uči me in si zapomnim, vključi me in se naučim.|Benjamin Franklin",
"Vlaganje v znanje prinaša najboljše obresti.|Benjamin Franklin",
"Ne odlašaj do jutri s tem, kar lahko storiš danes.|Benjamin Franklin",
"Izgubljenega časa ni več mogoče najti.|Benjamin Franklin",
"Nič ni tako močno kot ideja, ki ji je prišel čas.|Victor Hugo",
"Kdor odpre šolo, zapre zapor.|Victor Hugo",
"Največja sreča v življenju je prepričanje, da smo ljubljeni.|Victor Hugo",
"Glasba izraža tisto, česar ni mogoče povedati in o čemer ni mogoče molčati.|Victor Hugo",
"Pogum je vedeti, česa se ne bati.|Platon",
"Vsak človek se lahko nauči karkoli, če se tega loti na pravi način.|Platon",
"Dobro življenje ni vprašanje dolžine, ampak globine.|Seneka",
"Sreča ni nekaj gotovega; je nekaj, kar narediš.|Aristotel",
"Ni znanja, ki bi bilo odveč.|Leonardo da Vinci",
"Kdor želi doseči veliko, mora najprej obvladati malo.|Konfucij",
"Ne boj se počasnega napredka, boj se le nepremičnosti.|Konfucij",
"Tam, kjer se konča beseda, se začne glasba.|Heinrich Heine",
"Kjer sežigajo knjige, na koncu sežigajo tudi ljudi.|Heinrich Heine",
"Prava umetnost je skriti umetnost.|Ovid",
"Sreča spremlja pogumne.|Vergil",
"Zmagajo tisti, ki verjamejo, da zmorejo.|Vergil",
"Ni bogastva nad zdravjem, ne veselja nad srčnim veseljem.|Sirah",
"Vsaka pot se začne z odločitvijo, da ne ostaneš tam, kjer si.|Lao Ce",
"Trdo delo premaga talent, kadar talent ne dela trdo.|Tim Notke",
"Kdor ne stori napake, ne stori ničesar.|Giacomo Puccini",
"Delo, ki ga opraviš z ljubeznijo, ni nikoli izgubljeno.|Lev Tolstoj",
"Vsak konec je začetek nečesa novega.|Seneka",
"Ne obžaluj tega, kar se je končalo; bodi hvaležen, da se je zgodilo.|Mark Twain",
"Če hočeš iti hitro, pojdi sam. Če hočeš iti daleč, pojdi z drugimi.|afriški pregovor",
"Najboljši čas za sajenje drevesa je bil pred dvajsetimi leti. Drugi najboljši čas je zdaj.|kitajski pregovor",
"Pade sedemkrat, vstani osemkrat.|japonski pregovor",
"Počasi se daleč pride.|slovenski pregovor",
"Kdor ne vpraša, ostane neumen.|slovenski pregovor",
"Vsak začetek je težak.|slovenski pregovor",
"Zrno do zrna pogača, kamen do kamna palača.|slovenski pregovor",
"Kdor visoko leta, nizko pade; kdor pa vztraja, pride do cilja.|slovenski pregovor",
"Brez muje se še čevelj ne obuje.|slovenski pregovor",
"Kar se Janezek nauči, to Janez zna.|slovenski pregovor"
];
